# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb/message.proto',
  package='grpc_pub.pb',
  syntax='proto3',
  serialized_options=b'\n\020com.shiroha.grpcB\024MessageExchangeProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10pb/message.proto\x12\x0bgrpc_pub.pb\"!\n\x0eMessageRequest\x12\x0f\n\x07message\x18\x01 \x01(\x0c\"\"\n\x0fMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2]\n\x0fMessageExchange\x12J\n\x0bSendMessage\x12\x1b.grpc_pub.pb.MessageRequest\x1a\x1c.grpc_pub.pb.MessageResponse\"\x00\x42*\n\x10\x63om.shiroha.grpcB\x14MessageExchangeProtoP\x01\x62\x06proto3'
)




_MESSAGEREQUEST = _descriptor.Descriptor(
  name='MessageRequest',
  full_name='grpc_pub.pb.MessageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='grpc_pub.pb.MessageRequest.message', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=66,
)


_MESSAGERESPONSE = _descriptor.Descriptor(
  name='MessageResponse',
  full_name='grpc_pub.pb.MessageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='grpc_pub.pb.MessageResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['MessageRequest'] = _MESSAGEREQUEST
DESCRIPTOR.message_types_by_name['MessageResponse'] = _MESSAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MessageRequest = _reflection.GeneratedProtocolMessageType('MessageRequest', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEREQUEST,
  '__module__' : 'pb.message_pb2'
  # @@protoc_insertion_point(class_scope:grpc_pub.pb.MessageRequest)
  })
_sym_db.RegisterMessage(MessageRequest)

MessageResponse = _reflection.GeneratedProtocolMessageType('MessageResponse', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGERESPONSE,
  '__module__' : 'pb.message_pb2'
  # @@protoc_insertion_point(class_scope:grpc_pub.pb.MessageResponse)
  })
_sym_db.RegisterMessage(MessageResponse)


DESCRIPTOR._options = None

_MESSAGEEXCHANGE = _descriptor.ServiceDescriptor(
  name='MessageExchange',
  full_name='grpc_pub.pb.MessageExchange',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=104,
  serialized_end=197,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendMessage',
    full_name='grpc_pub.pb.MessageExchange.SendMessage',
    index=0,
    containing_service=None,
    input_type=_MESSAGEREQUEST,
    output_type=_MESSAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSAGEEXCHANGE)

DESCRIPTOR.services_by_name['MessageExchange'] = _MESSAGEEXCHANGE

# @@protoc_insertion_point(module_scope)
